baseURL = "https://pliutau.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Alex Pliutau - Blog"
theme = "anatole"
summarylength = 25
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "G-J98HDV96R0"
gtagId = "G-J98HDV96R0"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true


[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'onedark'
tabWidth = 4

[params]
googleAnalytics = "G-J98HDV96R0"
gtagId = "G-J98HDV96R0"
title = "Alex Pliutau"
author = "Alex Pliutau"
copyright = "2025"
description = "Staff SWE @BINARLY\nPassionate about Backend, Go, DevOps."
profilePicture = "/me.jpg"
keywords = "backend, golang, programming, devops, microservices, cloud, kubernetes, api, software"
favicon = "/"
customCss = []
customJs = []
mainSections = ["post"]
doNotLoadAnimations = false
displayMode = "light"

## Social links
[[params.socialIcons]]
title = "github"
url = "https://github.com/plutov"

[[params.socialIcons]]
title = "x"
url = "https://x.com/pliutau"

[[params.socialIcons]]
title = "youtube"
url = "https://www.youtube.com/@packagemain"

[[params.socialIcons]]
title = "email"
url = "mailto:alex.pliutau@gmail.com"

## Menu items
[menu]

[[menu.main]]
name = "Blog"
url = "/"
weight = 1

[[menu.main]]
name = "Newsletter"
url = "https://packagemain.tech/"
weight = 1

[[menu.main]]
name = "Now"
url = "/now/"
weight = 1

[deployment]

[[deployment.targets]]
name = "s3"
URL = "s3://pliutau.com?region=us-east-1"
cloudFrontDistributionID = "E1OWQZ20D426RZ"

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
