baseURL = "https://pliutau.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Alex Pliutau - Blog"
theme = "anatole"
summarylength = 25
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "G-J98HDV96R0"
gtagId = "G-J98HDV96R0"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true


[markup]
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'onedark'
tabWidth = 4

[params]
googleAnalytics = "G-J98HDV96R0"
gtagId = "G-J98HDV96R0"
title = "Hi👋, I'm Alex Pliutau"
author = "Alex Pliutau"
copyright = "2024"
description = "SWE passionate about Backend, Go, Cloud, DevOps, APIs, Kubernetes. Writing packagemain.tech newsletter. Currently leading an engineering team @Solsten"
profilePicture = "/me.png"
keywords = "backend, golang, programming, devops, microservices, cloud, kubernetes, api, software"
favicon = "/"
customCss = []
customJs = []
mainSections = ["post"]
doNotLoadAnimations = false
displayMode = "light"

[params.simpleAnalytics]

[params.math]
enable = false # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex" # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-youtube"
title = "GitHub"
url = "https://www.youtube.com/packagemain"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/plutov"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "GitHub"
url = "https://twitter.com/pliutau"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "http://linkedin.com/in/pltvs"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:alex.pliutau@gmail.com"

## Menu items
[menu]

[[menu.main]]
name = "Blog"
url = "/"
weight = 1

[[menu.main]]
name = "Newsletter"
url = "https://packagemain.tech/"
weight = 1

[[menu.main]]
name = "Now"
url = "/now/"
weight = 1

[deployment]

[[deployment.targets]]
name = "s3"
URL = "s3://pliutau.com?region=us-east-1"
cloudFrontDistributionID = "E1OWQZ20D426RZ"

[[deployment.matchers]]
pattern = "^.+\\.(html|xml|json)$"
gzip = true
