baseURL = "https://pliutau.com"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Alex Pliutau Blog"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
googleAnalytics = "G-J98HDV96R0"
gtagId = "G-J98HDV96R0"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
googleAnalytics = "G-J98HDV96R0"
gtagId = "G-J98HDV96R0"
title = "I'm Alex Pliutau"
author = "Alex Pliutau"
copyright = "2024"
description = "Software Engineering Lead passionate about Backend, Cloud, DevOps, APIs, Kubernetes, Go. Currently leading an engineering team at Solsten."
profilePicture = "/me.png"
keywords = "backend, go, golang, programming, devops, microservices, cloud, kubernetes, api"
favicon = "/"
customCss = []
customJs = []
mainSections = ["post"]
doNotLoadAnimations = false
displayMode = "light"

[params.simpleAnalytics]

[params.math]
enable = false # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex" # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-youtube"
title = "GitHub"
url = "https://www.youtube.com/packagemain"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/plutov"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "GitHub"
url = "https://twitter.com/pliutau"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "http://linkedin.com/in/pltvs"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:a@pliutau.com"

## Menu items
[menu]

[[menu.main]]
name = "Blog"
url = "/"
weight = 1

[[menu.main]]
name = "Substack"
url = "https://packagemain.tech/"
weight = 2

[deployment]

[[deployment.targets]]
name = "s3"
URL = "s3://pliutau.com?region=us-east-1"
cloudFrontDistributionID = "E1OWQZ20D426RZ"
